version: '3.8'

services:
  web:
    build: .
    container_name: flask_web
    ports:
      - "5000:5000"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
